AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'node_modules/**/*'
   - 'vendor/gems/**/*'
   - 'vendor/bundle/**/*'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
