require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - "**/*.rb"
    - "**/*.ru"
    - "**/*.rake"

  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'node_modules/**/*'
   - 'vendor/gems/**/*'
   - 'vendor/bundle/**/*'
Rails:
  Enabled: true
Layout/LineLength:
  Max: 100


