#User::Idenity used when creatin Contacts for current user (adding more his/her emails)
class User::Identity::AsContact < User::Identity   #< ActiveType::Record[User::Idenity] 
  validate :have_local_provider

  private

    def have_local_provider
      unless self.local?
        self.errors.add(:provider, "Must be local provider") 
        self.errors.delete(:uid) #for 'local' uid is autogenerated before validation
      end  
    end
end
